---
- name: install nginx
  apt:
    name: nginx
    state: latest
- name: start nginx
  service:
    name: nginx
    state: started
- name: copy the nginx config
  copy:
    src: ../config/back_nginx.cfg
    dest: /etc/nginx/sites-available/webapp.cfg
- name: restart nginx
  service: name=nginx state=restarted enabled=yes
