---
- hosts: front
  tasks:
    - name: stop nginx server
      service: name=nginx state=stopped enabled=no
    - name: deleting destination folder
      file:
        state: absent
        path: "/var/www/html"
    - name: recreating destination folder
      file:
        state: directory
        path: "/var/www/html"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        recurse: yes
    - name: Copy front build directory
      copy: src=/home/gitlab-runner/builds/XJGkXp2X/0/root/t-nsa/frontend/dist/front/* dest=/var/www/html
    - name: restart nginx server
      service: name=nginx state=restarted enabled=yes
