---
- hosts: db
  tasks:
    - name: checking mysql server is running
      service: name=mysql state=started enabled=no
    - name: deleting destination folder
      file:
        state: absent
        path: "/var/www/back"
    - name: recreating destination folder
      file:
        state: directory
        path: "/var/www/back"
    - name: Copy back directory which is containing the db migrations
      copy: src=/home/gitlab-runner/builds/XJGkXp2X/0/root/t-nsa/backend/ dest=/var/www/back
    - name: run db migration
      shell: php artisan migrate:rollback --force
      args:
        chdir: /var/www/back/backend/
