stages:
  - build
  - test
#  - deploy

front build:
  tags:
    - ci
  image: node:latest
  stage: build
  cache:
    paths:
      - frontend/node_modules/
      - frontend/dist/
  script:
    - cd frontend
    - npm install --allow-root --unsafe-perm
    - npm run build
  artifacts:
    paths:
      - frontend/dist/

front test:
  tags:
    - ci
  image: node:latest
  stage: test
  cache:
    policy: pull
    paths:
      - frontend/node_modules/
      - frontend/dist/
  script:
    - cd frontend
    - npm run test

# Back
back build:
  tags:
    - ci
  stage: build
  variables:
    NODE_ENV: development
  before_script:
    - cd backend
    - yarn install
    - composer install
  script:
    - npm build

back tests:
  tags:
    - ci
  stage: test
  variables:
    NODE_ENV: development
  before_script:
    - cd backend
    - yarn install
    - composer install
  script:
    - vendor/bin/phpunit ./tests/Unit
# Front
#front build:
#  image: node:latest
#  stage: build
#  before_script:
#    - cd front
#    - npm install
#    - npm install --save-dev
#  script:
#    - npm run build

#frontend tests:
#  image: weboaks/node-karma-protractor-chrome
#  stage: test
#  before_script:
#    - cd front
#    - npm install
#    - npm install --save-dev
#    - npm install -g npx
#    - npx webdriver-manager clean
#    - npx webdriver-manager update
#  script:
#    - npm test
#    - npm run e2e
