stages:
  - build
  - test
  - deploy

front build:
  tags:
    - ci
  image: node:latest
  stage: build
  cache:
    paths:
      - frontend/node_modules/
      - frontend/dist/
  script:
    - cd frontend
    - npm install --allow-root --unsafe-perm
    - npm run build
  artifacts:
    paths:
      - frontend/dist/

front test:
  tags:
    - ci
  image: node:latest
  stage: test
  cache:
    policy: pull
    paths:
      - frontend/node_modules/
      - frontend/dist/
  script:
    - cd frontend
    - npm run test

front release:
  tags:
    - ci
  image: node:latest
  stage: deploy
  cache:
    policy: pull
    paths:
      - frontend/node_modules/
      - frontend/dist/
  script:
    - sudo ansible-playbook /etc/ansible/release_front.yml

# Back
back build:
  tags:
    - ci
  stage: build
  variables:
    NODE_ENV: development
  before_script:
    - cd backend
    - yarn install
    - composer install
  script:
    - npm build

back tests:
  tags:
    - ci
  stage: test
  variables:
    NODE_ENV: development
  before_script:
    - cd backend
    - yarn install
    - composer install
  script:
    - vendor/bin/phpunit ./tests/Unit

back release:
  tags:
    - ci
  stage: deploy
  before_script:
    - cd backend
    - yarn install
    - composer install
  script:
    - sudo ansible-playbook /etc/ansible/release_back.yml

# DB
db release:
  tags:
    - ci
  stage: deploy
  script:
    - sudo ansible-playbook /etc/ansible/release_db.yml
