---
- name: Add PHP 7 PPA repository
  apt_repository:
    repo: "ppa:ondrej/php"
- name: install php
  apt:
    pkg:
      - php7.3-fpm
      - openssl
      - php-common
      - php-curl
      - php-json
      - php-mbstring
      - php-mysql
      - php-xml
      - php-zip
      - php7.3-common
      - php7.3-bcmath
      - php7.3-json
      - php7.3-mbstring
