---
- name: create database
  mysql_db:
    name: tnsadb
    login_unix_socket: /run/mysqld/mysqld.sock
    state: present
- name: install rpl
  apt:
    name: rpl
- name: authorize all ips to connect to the db
  command: sudo rpl "127.0.0.1" "0.0.0.0" /etc/mysql/mysql.conf.d/mysqld.cnf
- name: restart mysql
  command: sudo systemctl restart mysql
