---
- name: install nginx
  apt:
    name: nginx
    state: latest
- name: start nginx
  service:
    name: nginx
    state: started
- name: copy the nginx config file
  copy:
    src: /etc/ansible/roles/back_nginx_install/files/back.cfg
    dest: /etc/nginx/sites-available/back.cfg
- name: create symlink to config
  file:
    src: /etc/nginx/sites-available/back.cfg
    dest: /etc/nginx/sites-enabled/default
    state: link
- name: restart nginx
  service: name=nginx state=restarted enabled=yes
